config/routes.rb
Zweeter::Application.routes.draw do
  resources :eadibilities

  resources :graveyards

  get "zombies/index"
  get "zombies/show"
  get "zombies/new"
  get "zombies/edit"
  get "zombies/create"
  get "zombies/update"
  get "zombies/destroy"
  get "tweets/index"
  get "tweets/show"
  get "tweets/new"
  get "tweets/edit"
  get "tweets/create"
  get "tweets/update"
  get "tweets/destroy"
  

end

app/models/eadibility.rb
class Eadibility < ActiveRecord::Base
  belongs_to :graveyard
end

app/models/graveyard.rb
class Graveyard < ActiveRecord::Base
  has_many :eadimilitys
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :zombie
end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/eadibilities_controller.rb
class EadibilitiesController < ApplicationController
end

app/controllers/graveyards_controller.rb
class GraveyardsController < ApplicationController
  before_action :set_graveyard, only: [:show, :edit, :update, :destroy]

  # GET /graveyards
  # GET /graveyards.json
  def index
    @graveyards = Graveyard.all
  end

  # GET /graveyards/1
  # GET /graveyards/1.json
  def show
  end

  # GET /graveyards/new
  def new
    @graveyard = Graveyard.new
  end

  # GET /graveyards/1/edit
  def edit
  end

  # POST /graveyards
  # POST /graveyards.json
  def create
    @graveyard = Graveyard.new(graveyard_params)

    respond_to do |format|
      if @graveyard.save
        format.html { redirect_to @graveyard, notice: 'Graveyard was successfully created.' }
        format.json { render action: 'show', status: :created, location: @graveyard }
      else
        format.html { render action: 'new' }
        format.json { render json: @graveyard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /graveyards/1
  # PATCH/PUT /graveyards/1.json
  def update
    respond_to do |format|
      if @graveyard.update(graveyard_params)
        format.html { redirect_to @graveyard, notice: 'Graveyard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @graveyard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graveyards/1
  # DELETE /graveyards/1.json
  def destroy
    @graveyard.destroy
    respond_to do |format|
      format.html { redirect_to graveyards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_graveyard
      @graveyard = Graveyard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def graveyard_params
      params.require(:graveyard).permit(:name, :capacity)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @zombie= Zombie.new(params[:zombie])
    @zombie.save
    redirect_to @zombie
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eadibilities_helper.rb
module EadibilitiesHelper
end

app/helpers/graveyards_helper.rb
module GraveyardsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/graveyards/_form.html.erb
<%= form_for(@graveyard) do |f| %>
  <% if @graveyard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@graveyard.errors.count, "error") %> prohibited this graveyard from being saved:</h2>

      <ul>
      <% @graveyard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/graveyards/edit.html.erb
<h1>Editing graveyard</h1>

<%= render 'form' %>

<%= link_to 'Show', @graveyard %> |
<%= link_to 'Back', graveyards_path %>

app/views/graveyards/index.html.erb
<h1>Listing graveyards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Capacity</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @graveyards.each do |graveyard| %>
      <tr>
        <td><%= graveyard.name %></td>
        <td><%= graveyard.capacity %></td>
        <td><%= link_to 'Show', graveyard %></td>
        <td><%= link_to 'Edit', edit_graveyard_path(graveyard) %></td>
        <td><%= link_to 'Destroy', graveyard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Graveyard', new_graveyard_path %>

app/views/graveyards/new.html.erb
<h1>New graveyard</h1>

<%= render 'form' %>

<%= link_to 'Back', graveyards_path %>

app/views/graveyards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @graveyard.name %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @graveyard.capacity %>
</p>

<%= link_to 'Edit', edit_graveyard_path(@graveyard) %> |
<%= link_to 'Back', graveyards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zweeter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/destroy.html.erb
<h1>Tweets#destroy</h1>
<p>Find me in app/views/tweets/destroy.html.erb</p>

app/views/tweets/edit.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>
<table>
  <tr>
    <th>Status</th>
    <th>Zombie</th>
  </tr>
  <% Tweet.all.each do |t| %>
    <tr>
      <td><%= t.status %></td>
      <td><%= t.zombie.name %></td>
    </tr>
   <% end %>
</table>

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<% tweet=Tweet.find(1) %>
<h1><%= tweet.status  %></h1>
<p>Posted by <%= link_to tweet.zombie.name, zombie_path(tweet.zombie) %></p>
<p>Other way tu use <e>link_to</e>:<br/>
Posted by <%= link_to tweet.zombie.name, tweet.zombie %></p>

app/views/tweets/update.html.erb
<h1>Tweets#update</h1>
<p>Find me in app/views/tweets/update.html.erb</p>

app/views/zombies/create.html.erb
<h1>Zombies#create</h1>
<p>Find me in app/views/zombies/create.html.erb</p>

app/views/zombies/destroy.html.erb
<h1>Zombies#destroy</h1>
<p>Find me in app/views/zombies/destroy.html.erb</p>

app/views/zombies/edit.html.erb
<h1>Zombies#edit</h1>
<p>Find me in app/views/zombies/edit.html.erb</p>

app/views/zombies/index.html.erb
<h1>Zombies#index</h1>
<p>Find me in app/views/zombies/index.html.erb</p>

app/views/zombies/new.html.erb
<h1>Zombies#new</h1>
<p>Find me in app/views/zombies/new.html.erb</p>

app/views/zombies/show.html.erb
<h1>Zombies#show</h1>
<p>Find me in app/views/zombies/show.html.erb</p>

app/views/zombies/update.html.erb
<h1>Zombies#update</h1>
<p>Find me in app/views/zombies/update.html.erb</p>